apiVersion: apps/v1
kind: Deployment
metadata:
  name: langflow-worker
  labels:
    app: langflow-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langflow-worker
  template:
    metadata:
      labels:
        app: langflow-worker
    spec:
      containers:
        - name: langflow-worker
          image: ${REGISTRY_HOST}:30500/${BUILT_IMAGE}
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: langflow-worker-config
            - secretRef:
                name: langflow-secret
          env:
            - name: POSTGRES_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: langflow-config
                  key: POSTGRES_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              value: "pgbouncer"
            - name: POSTGRES_PORT
              value: "6432"
            - name: LANGFLOW_DATABASE_URL
              value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB_NAME)"
          command: [ "/bin/sh","-lc" ]
          args:
            - >
              exec /app/.venv/bin/python -m celery
              -A langflow.worker worker
              --loglevel=info
              --concurrency=${CELERY_CONCURRENCY:-4} # Ezt a configmapból vesszük
          volumeMounts:
            - name: tis-components
              mountPath: /app/tis_components
            - name: flows-data
              mountPath: /app/flows
            - name: logs-data
              mountPath: /app/logs
            - name: init-scripts-python
              mountPath: /app/init/python
      volumes:
        - name: tis-components
          hostPath:
            path: /workspace/kubernetes/langflow/src/tis_components/
            type: Directory
        - name: flows-data
          persistentVolumeClaim:
            claimName: langflow-flows-pvc
        - name: logs-data
          persistentVolumeClaim:
            claimName: langflow-logs-pvc
        - name: init-scripts-python
          hostPath:
            path: /workspace/kubernetes/langflow/init/python/
            type: Directory
